project_id = "gnolgoyhqbqilkgaakgj"

[auth]
site_url = "https://comfy-home-spot.lovable.app"
additional_redirect_urls = ["https://comfy-home-spot.lovable.app"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

# Custom SMTP settings - Zoho Mail
[auth.email.smtp]
host = "smtp.zoho.com"
port = 587
user = ""
pass = ""
admin_email = "admin@dwellmerge.com"
sender_name = "DwellMerge"