project_id = "gnolgoyhqbqilkgaakgj"

[auth]
site_url = "https://dwellmerge.com"
additional_redirect_urls = ["https://dwellmerge.com", "https://www.dwellmerge.com", "https://dwellmerge.vercel.app"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

# Custom SMTP settings - Zepto Mail
[auth.email.smtp]
host = "smtp.zeptomail.com"
port = 587
user = "env(ZEPTO_MAIL_SMTP_USER)"
pass = "env(ZEPTO_MAIL_SMTP_PASS)"
admin_email = "admin@dwellmerge.com"
sender_name = "DwellMerge"